/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java.code.analysis.kotlin-library-conventions")
}

dependencies {
    implementation(gradleApi())
}
